### ISSUE TITLE
Need a way to re-load list of options onFocus of CustomDropdown or onChange of another Dropdown or selection

### ISSUE THREAD

**Issue by NOA-Alex** [mendixlabs/CustomDropdown#37]
A larger record could contain multiple CustomDropdowns which depend on each other.

An INVOICE might contain a dropdown for a CLIENT. And then a dropdown for an ORDER. Pre-filtered by orders which belong to the already selected client.

Which works currently only if the user selects first the CLIENT and only after that clicks the first time on the ORDER dropdown. Once the ORDER dropdown is clicked once the list of options is already loaded. Even the user removes or changes the CLIENT the list of options for ORDERS remains the same. Even if I refresh (or even delete) the CustomDropdownContext in a Microflow or Nanoflow or the INVOICE DataView which contains the dropdown. The only way which works is to reload the entire page. Which is not a good user experience.

It would be great if
- EITHER the first dropdown could refresh onChange the second dropdown (for example via Microflow or Nanoflow).
- OR the second dropdown could refresh onClick or onFocus or onReFocus the list of options.

Maybe that could be also an additional option which can be switched on only if needed (like in this case where the options from the one dropdown depend on another selection).

**Comment by JansenNick** [comment]
Hi Alex,
Nice to hear you are using the widget! What you describe was indeed an issue, @NammNguyen and @BananiMendix ran into the same thing and opened a pull request that solves this issue. I just created a release and published the new version in the mendix marketplace. The new version has added a boolean named "Refresh on context change" in the options section, set it to Yes and make sure you create a new context object each time you want to refresh the default options. I hope this also solves your problem.

https://github.com/mendixlabs/CustomDropdown/releases/tag/2.4.0

**Comment by NOA-Alex** [comment]
Dear Nick,
You made my day :-)

I updated to the CustomDropdown to the new version released by you, let Mendix update the definition of 56 widgets, activated the boolean "Refresh on context change" for the few dropdowns where I needed, modified the onChange Nanoflow and it works like a charm :-)

Thanks a lot for the super fast update here. Highly appreciated!

Regards,
Alex
